name: "Multi event pipleline/workflow" # Name of the pipeline

on:
    push: # Event: Whenever a push is made to the repository on the master branch
        branches:
            - master
            - test
    schedule:
        - cron: "0 10 * * 2,4" # Event: Every Tuesday and Thursday at 10:00 AM
    pull_request: # Event: Whenever a pull request is made to the repository
            branches:
                - master
            types:
                - closed
                - opened
    workflow_dispatch: # Event: A UI button will be given to execute the workflow


jobs:
    on-push: # Job name
        # Run only if event is push
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master/test push" # Step 1
              run: echo "Running on master/test push"

    on-pull-request: # Job name
        # Run only if event is pull_request
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master/test pull_request" # Step 1
              run: echo "Running on master/test pull_request"

    on-pull-request-closed: # Job name
        # Run only if event is pull_request and type is closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master/test pull_request closed" # Step 1
              run: echo "Running on master/test pull_request closed"

    on-workflow-dispatch: 
        # Run only if event is workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master/test workflow_dispatch" # Step 1
              run: echo "Running on master/test workflow_dispatch"

    on-schedule: 
        # Run only if event is workflow_dispatch
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master/test schedule" # Step 1
              run: echo "Running on master/test schedule"